version: "2"

linters:
  disable:
  - errcheck
  settings:
    staticcheck:
      checks:
      - all
      # ST1000: at least one file in a package should have a package comment
      - "-ST1000"
      # QF1008: could remove embedded field "..." from selector
      - "-QF1008"