package main

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"os"
	"strings"

	"github.com/grafana/generate-policy-bot-config/internal"
	"github.com/jessevdk/go-flags"
	"github.com/lmittmann/tint"
	"github.com/palantir/policy-bot/policy"
	"github.com/willabides/actionslog"
	"github.com/willabides/actionslog/human"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

func header(programName string, mergeFilename string) string {
	sb := strings.Builder{}
	sb.WriteString("# This file is generated by ")
	sb.WriteString(programName)
	sb.WriteString(".\n# Do not edit directly. Run \"make .policy.yml\" to update.")

	if mergeFilename != "" {
		sb.WriteString("\n\n# The contents of \"")
		sb.WriteString(mergeFilename)
		sb.WriteString("\" were merged with the generated parts of this config.\n")
		sb.WriteString("# To add additional policies to the config, update this file and then run \"make .policy.yml\".")
	}

	sb.WriteString("\n\n")

	return sb.String()
}

const description = "Discovers GitHub Actions workflows and generates a policy bot configuration " +
	"file which enforces that they pass. If paths are specified in the workflow, the policy " +
	"will enforce that the workflow passes only when the paths are modified in the PR."

// rootDir represents the root directory to search for workflows. It is a
// wrapper around fs.FS which reads from a directory when unmarshaled from a
// flag. It exists so that the filesystem can be faked in tests.
type rootDir struct {
	fs.FS
}

func (rd *rootDir) UnmarshalFlag(value string) error {
	*rd = rootDir{os.DirFS(value)}
	return nil
}

// reader is the config to merge with the generated config. A nil Reader means
// that no merging occurs. The filename is empty when reading from standard
// input.
type reader struct {
	filename string
	io.Reader
}

// mergeSource is where to read the config to merge with the generated config,
// as given by --merge-with. If the value is "-", read from standard input. If
// the value is empty, no merging occurs. Otherwise, read from the file at the
// given path.
type mergeSource struct {
	stdin bool
	path  string
}

func (m *mergeSource) UnmarshalFlag(value string) error {
	switch value {
	case "":
		*m = mergeSource{}
	case "-":
		*m = mergeSource{stdin: true}
	default:
		*m = mergeSource{path: value}
	}

	return nil
}

// open opens the config to merge. A file is opened with openFile.
func (m mergeSource) open(openFile func(name string) (io.Reader, error), stdin io.Reader) (reader, error) {
	if m.stdin {
		return reader{Reader: stdin}, nil
	}

	if m.path == "" {
		return reader{}, nil
	}

	file, err := openFile(m.path)
	if err != nil {
		return reader{}, fmt.Errorf("failed to open merge file: %w", err)
	}

	return reader{Reader: file, filename: m.path}, nil
}

func openFile(name string) (io.Reader, error) {
	return os.Open(name)
}

// output is where to write the generated config, as given by --output. If the
// value is "-", write to standard output. Otherwise, write to the file at the
// given path.
type output struct {
	stdout bool
	path   string
}

func (o *output) UnmarshalFlag(value string) error {
	if value == "-" {
		*o = output{stdout: true}
		return nil
	}

	*o = output{path: value}
	return nil
}

// write calls generate with a writer for this output. A file is written to a
// temporary file in fsys, which is only renamed into place if generate
// succeeds.
func (o output) write(fsys internal.WritableFS, stdout io.Writer, generate func(io.Writer) error) error {
	if o.stdout {
		return generate(stdout)
	}

	w, err := internal.NewRenamingWriter(fsys, o.path)
	if err != nil {
		return err
	}

	if err := generate(w); err != nil {
		if abortErr := w.Abort(); abortErr != nil {
			slog.Warn("failed to abort", "error", abortErr)
		}

		return err
	}

	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to write output: %w", err)
	}

	return nil
}

type level slog.Level

func (l *level) UnmarshalFlag(value string) error {
	var lvl slog.Level
	err := lvl.UnmarshalText([]byte(value))
	if err != nil {
		return fmt.Errorf("invalid log level: %w", err)
	}

	*l = level(lvl)
	return nil
}

type rootArgs struct {
	Root rootDir `positional-arg-name:"REPO_ROOT"`
}

type appFlags struct {
	Output    output      `long:"output" short:"o" description:"Output file. If this is \"-\", write to standard output" default:".policy.yml"`
	LogLevel  *level      `long:"log-level" short:"l" description:"Log level"`
	MergeWith mergeSource `long:"merge-with" short:"m" description:"File to merge with generated config. If this is \"-\", read from standard input. If empty, no merging occurs."`

	Args rootArgs `positional-args:"yes" required:"yes"`
}

// listWorkflows returns a list of all the workflows under the root directory
// given in the arguments.
func (af *appFlags) listWorkflows() ([]string, error) {
	ymlFiles, err := fs.Glob(af.Args.Root, ".github/workflows/*.yml")
	if err != nil {
		return nil, fmt.Errorf("failed to list workflows: %w", err)
	}

	yamlFiles, err := fs.Glob(af.Args.Root, ".github/workflows/*.yaml")
	if err != nil {
		return nil, fmt.Errorf("failed to list workflows: %w", err)
	}

	allWorkflows := append(ymlFiles, yamlFiles...)

	if len(allWorkflows) == 0 {
		return nil, internal.ErrNoWorkflows{}
	}

	slog.Debug("Found workflows", "num_workflows", len(allWorkflows))
	return allWorkflows, nil
}

// parsePRWorkflows parses all the workflows under the root directory given in
// the arguments and returns a map of the workflows that are `pull_request`
// or `pull_request_target` workflows. The key is the path to the workflow file
// and the value is the parsed workflow. Workflows that are not `pull_request`
// or `pull_request_target`, as well as invalid workflows which cannot be
// parsed or read, are ignored. The only way this function can fail is if it
// encounters an error while listing the workflows.
func (af *appFlags) parsePRWorkflows() (internal.GitHubWorkflowCollection, error) {
	paths, err := af.listWorkflows()
	if err != nil {
		return nil, err
	}

	workflows := make(map[string]internal.GitHubWorkflow)

	for _, workflowPath := range paths {
		contents, err := fs.ReadFile(af.Args.Root, workflowPath)
		if err != nil {
			slog.Warn("failed to read workflow", "path", workflowPath, "error", err)
			continue
		}

		slog.Debug("parsing workflow", "path", workflowPath)
		var workflow internal.GitHubWorkflow
		err = yaml.Unmarshal(contents, &workflow)
		if err != nil {
			err = internal.ErrInvalidWorkflow{Path: workflowPath, Err: err}
			slog.Warn("failed to parse workflow", "path", workflowPath, "error", err)
			continue
		}

		if !workflow.IsPullRequestWorkflow() {
			slog.Debug("skipping non-PR workflow", "path", workflowPath)
			continue
		}

		// We can't assume that there will be a workflow run if the PR doesn't
		// run on `synchronize`, so we skip enforcing the workflow for this
		// case. For example, if `types` is `[opened]`, a run will only be
		// present when the PR is first opened but if it gets another push then
		// there won't be one.
		if !workflow.RunsOnSynchronize() {
			slog.Debug("skipping workflow that doesn't run on synchronize", "path", workflowPath)
			continue
		}

		workflows[workflowPath] = workflow
	}

	return workflows, nil
}

// loadConfigFromReader reads a policy bot config from the given reader. This is
// used to merge the generated config with an existing config.
//
// The config is decoded twice. Once into policy-bot's own types, which we throw
// away: it is there to reject a config that policy-bot couldn't load, which is
// worth catching here rather than several steps later. And once into our own
// type, which keeps the hand-written parts as raw YAML so that merging can't
// change what they mean. See internal.Config.
func loadConfigFromReader(r io.Reader) (internal.Config, error) {
	raw, err := io.ReadAll(r)
	if err != nil {
		return internal.Config{}, fmt.Errorf("failed to read config: %w", err)
	}

	var validated policy.Config
	if err := yaml.NewDecoder(bytes.NewReader(raw)).Decode(&validated); err != nil {
		return internal.Config{}, internal.ErrInvalidPolicyBotConfig{Err: err}
	}

	var config internal.Config
	if err := yaml.Unmarshal(raw, &config); err != nil {
		return internal.Config{}, internal.ErrInvalidPolicyBotConfig{Err: err}
	}

	return config, nil
}

func (af *appFlags) run(name string, merge reader, w io.Writer) error {
	// Find and parse all the workflows
	workflows, err := af.parsePRWorkflows()
	if err != nil {
		return err
	}

	// Generate a policy bot config from them
	generated := workflows.PolicyBotConfig()

	// The config to write out. With nothing to merge, the generated config goes
	// out as it is; there is no hand-written config to preserve.
	var config any = generated

	// Merge the generated config with an existing config, if one was provided
	if merge.Reader != nil {
		mergeConfig, err := loadConfigFromReader(merge)
		if err != nil {
			return err
		}

		merged, err := internal.MergeConfigs(generated, mergeConfig)
		if err != nil {
			return fmt.Errorf("failed to merge generated config with existing config: %w", err)
		}

		config = merged
	}

	// Write the config to the output file
	if _, err := w.Write([]byte(header(name, merge.filename))); err != nil {
		return fmt.Errorf("failed to write header: %w", err)
	}

	if err := internal.WriteYamlToWriter(w, config); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

func setupLogger() *slog.LevelVar {
	var lv slog.LevelVar

	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: &lv,
	}))
	defer func() { slog.SetDefault(logger) }()

	if os.Getenv("GITHUB_ACTIONS") == "true" {
		logger = slog.New(&actionslog.Wrapper{
			Handler: (&human.Handler{
				AddSource:   true,
				ExcludeTime: true,
				Level:       &lv,
			}).WithOutput,
			Output: os.Stderr,
		})

		if os.Getenv("RUNNER_DEBUG") == "1" {
			lv.Set(slog.LevelDebug)
		}
		return &lv
	}

	if term.IsTerminal(int(os.Stderr.Fd())) {
		logger = slog.New(tint.NewTextHandler(os.Stderr, &tint.Options{
			AddSource: true,
			Level:     &lv,
		}))
	}

	return &lv
}

func main() {
	lv := setupLogger()

	var conf appFlags
	parser := flags.NewParser(&conf, flags.Default)
	parser.LongDescription = description

	if _, err := parser.Parse(); err != nil {
		// The flags package has already printed the error, or the help text
		// for --help.
		if flags.WroteHelp(err) {
			os.Exit(0)
		}

		os.Exit(1)
	}

	if conf.LogLevel != nil {
		lv.Set(slog.Level(*conf.LogLevel))
	}
	slog.Debug("debug logging enabled")

	merge, err := conf.MergeWith.open(openFile, os.Stdin)
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}

	err = conf.Output.write(internal.OSFS{}, os.Stdout, func(w io.Writer) error {
		return conf.run(parser.Name, merge, w)
	})
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
}
